language: php
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
php:
  - 7.2
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
